### ISSUE TITLE
Its not work after update

### ISSUE THREAD

**Issue by hematube** [0mlml/chesshook#5] opened 2024-02-28 09:02 UTC
The render did not displayed after the last update and its not work

**Comment by 0mlml** [comment] 2024-02-28 12:21
Hi, could you please elaborate on what specifically isn't working?
Try clearing local storage to reset the configuration of the script by running "`window.localStorage.clear()`" in the developer console or clearing it with your browser

**Comment by hematube** [comment] 2024-02-28 13:21
> Hi, could you please elaborate on what specifically isn't working?
> Try clearing local storage to reset the configuration of the script by running "`window.localStorage.clear()`" in the developer console or clearing it with your browser

I have done everything, but the threat Arrow appear only towards me, it does not appear all the time either, only at certain times and nothing else appears

**Comment by hematube** [comment] 2024-02-28 13:21
Could you at least give me the old version

**Comment by 0mlml** [comment] 2024-02-28 14:47
Please send a picture of your config. This seems like it might be a configuration issue. 

Old versions can be found in the commit history. I've uploaded one such version [here](https://gist.github.com/0mlml/a9488931cc2fc8cb8884f116f40053c6) that has the update/download URLs removed.

**Comment by 0mlml** [comment] 2024-02-28 14:54
Greetings, upon further thought, it seems that you might be describing intended behavior. The threat arrows do not appear if there are no threats, and they only appear for the player whose turn it is.

I am going to close this issue. Please feel free to reopen it if this diagnosis is not correct.

Best Wishes

**Closed as completed by 0mlml** 2024-02-28 14:54 UTC
Labels: bug

**Comment by hematube** [comment] 2024-02-28 18:24
How could i turn on/off the automove system and is it cause ban?

**Comment by 0mlml** [comment] 2024-02-28 18:41
Automove is a simple checkbox in the config tab. Additional configuration options appear when the feature is enabled. The feature will then play the moves from the selected engine automatically. 

I am fairly confident that the feature itself is not detected (ergo simply having the feature enabled a playing moves will not cause a ban), but abusing it to play large amounts of games or top engine moves will obviously cause suspicion on your account.

**Comment by hematube** [comment] 2024-02-28 20:04
I qm sorry that i am asking alot but i can't turn automove  off cause i play on android not pc

**Comment by 0mlml** [comment] 2024-02-29 10:38
I cannot help you if you're on Android. I don't use the userscript on Android and did not even consider mobile users when creating the script.

**Comment by hematube** [comment] 2024-03-07 21:35
I have played 13 match with the auto move in a fake account and i got banned but i played 4 unrated match bullet wih automove with my friend in my real acc am i gonna banned?

**Comment by 0mlml** [comment] 2024-03-08 08:52
Hello, the 13 matches you played with automove likely would have gotten you banned due to the engine moves being played, regardless of whether or not you manually inputted the moves or used the feature. 

According to chess.com's TOS, you can use engines in unrated games as long as both parties are aware of the engine being used (impossible to prove; ergo you can cheat in unrated matches to your heart's content).

**Comment by hematube** [comment] 2024-03-09 03:06
Are you sure?
Because the new fair play update is saying that if you use engine in rated or unrated match they are the same that's what make me afraid to get banned
